implemented flags input validation

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -9,6 +9,15 @@ COMMAND=""
 FILE=""
 GZ_FILE=""
 
+checkDate(){
+    local status=1
+    if [[ $1 =~ ((18|19|20)[0-9]{2}[\-.](0[13578]|1[02])[\-.](0[1-9]|[12][0-9]|3[01]))|(18|19|20)[0-9]{2}[\-.](0[469]|11)[\-.](0[1-9]|[12][0-9]|30)|(18|19|20)[0-9]{2}[\-.](02)[\-.](0[1-9]|1[0-9]|2[0-8])|(((18|19|20)(04|08|[2468][048]|[13579][26]))|2000)[\-.](02)[\-.]29 ]];
+    then
+        status=0
+    fi
+    return $status
+}
+
 # Parsing filter tag and commands
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -26,37 +35,58 @@ while [ $# -gt 0 ]; do
         fi
         ;;
     -a)
-        # TODO - validate DATE input 
-        if [ "$2" = "" ]; then
+        if [ "$2" != "" ];
+        then
+            if checkDate "$2";
+            then
+                AFTER_DATE="$2"
+                echo $AFTER_DATE
+                shift
+                shift
+            else
+                echo -e "Wrong date format or missing date parameter"
+                exit 1
+            fi
+        else
             echo -e "-a: Missing date parameter"
             exit 1
         fi
-        AFTER_DATE="$2"
-        echo $AFTER_DATE
-        shift
-        shift
         ;;
     -b)
-        # TODO - validate DATE input
-        if [ "$2" = "" ]; then
-            echo -e "-b: Missing date parameter"
+        if [ "$2" != "" ];
+        then
+            if checkDate "$2";
+            then
+                BEFORE_DATE="$2"
+                echo $BEFORE_DATE
+                shift
+                shift
+            else
+                echo -e "Wrong date format or missing date parameter"
+                exit 1
+            fi
+        else
+            echo -e "-a: Missing date parameter"
             exit 1
         fi
-        BEFORE_DATE="$2"
-        echo $BEFORE_DATE
-        shift
-        shift
-        ;;       
+        ;;   
     -g)
-        # TODO - validate GENDER input
-        if [ "$2" = "" ]; then
+        if [ "$2" = "" ];
+        then
             echo -e "-g: Missing gender parameter"
             exit 1
         fi
-        GENDER="$2"
-        echo $GENDER
-        shift
-        shift
+        if [[ $2 =~ [MZ] ]];
+        then
+            GENDER="$2"
+            echo $GENDER
+            shift
+            shift
+        else
+            echo -e "Wrong gender format"
+            exit 1
+        fi
+        
         ;;
     -s)
         if [[ $2 =~ [0-9]{1} ]]; then
@@ -90,12 +120,19 @@ while [ $# -gt 0 ]; do
     esac
 done
 
+
+#TODO bzip2 file reading
+
 if [ "$FILE" != "" ]; then
     TEST=$(cat "$FILE" | awk 'END{print NR}')
     echo $TEST
+    else
+        FILE=`cat`
+        echo "$FILE"
 fi
 
 if [ "$GZ_FILE" != "" ]; then
     TEST=$(echo "$GZ_FILE" | awk 'END{print NR}')
     echo $TEST
 fi
+
